### ISSUE TITLE
Download stuck at 0B/s after some time

### ISSUE THREAD

**Issue by BigGDeX** [sirrobot01/decypharr#60]
Hello,
It's my first time using debrid service. 
I get this error
`context deadline exceeded (Client.Timeout or context cancellation while reading body)`
when the file is downloading. It reaches about 20-30% and then stops at 0B/s.
If I download the same file via webdav (browser) or Jdownloader it just works and saturate my connection.
What can be the cause?
Thank you

**Comment by sirrobot01** [comment]
Are you downloading locally or symlink? If downloading locally, Make sure you have a good internet. 

Also, providing the full log will help debug the issue.

**Comment by BigGDeX** [comment]
I'm downloading locally, I have a good connection, in fact if I try to download via browser or jdownload it works just fine. 
I had the same problem with rdt-client. I might start to think storage is my problem here, I will try with another disk. Can you please indicate what type of log level I need to post? 
Other info: I use it with docker, it's downloading the file on a 128gb usb stick (it was "temporary", but deluge worked and is working just fine for over an year at this point). I have a 200/50mbit connection.

**Comment by sirrobot01** [comment]
This is now fixed and in beta.

I'll close the issue when it gets to the main branch

**Comment by kennyparsons** [comment]
@sirrobot01 I'm on beta and am still getting this issue. Here's the full set of details:

The core issue is that the download context is being cancelled or timing out during transfer. A secondary issue is that decypharr logs the file as successfully downloaded even though the transfer was not completed.

---

### Primary Issue: Download context cancelled mid-download

This happens reliably during sequential downloads (ie. not symlinking).

Relevant log output:

```
2025-05-20 14:10:41 | INFO  | [qbit] Downloading 1 files...
2025-05-20 14:10:42 | DEBUG | [realdebrid-webdav] Processed 1 new torrents
2025-05-20 14:11:41 | ERROR | [qbit] Failed to download <filename.mkv>: context deadline exceeded (Client.Timeout or context cancellation while reading body)
2025-05-20 14:11:41 | INFO  | [qbit] Downloaded all files for <filename.mkv>
2025-05-20 14:11:41 | ERROR | [realdebrid-webdav] Failed to get torrents error="read tcp 172.18.0.2:44920->94.140.4.11:443: read: connection reset by peer"
```

---

### Secondary Issue: Incorrect success reporting

As shown above, decypharr logs:
```
INFO  | [qbit] Downloaded all files for <filename.mkv>
```
…immediately after logging a context deadline exceeded error, which is misleading. The file is incomplete.

---

### Manual Test

To isolate the problem, I manually accessed the decypharr WebDAV URL directly via browser  and downloaded the file:

- The download completed without interruption or error.
- decypharr did not log any issues during this manual transfer.
